language: node_js
node_js:
  - lts/*
services:
  - docker
install:
  - npm i -g tl @mapbox/mbtiles tilelive-http
  - npm i
before_script: bash pipeline.sh
script: npm test
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
